server:
  port: 9527
spring:
  application:
    name: aigou-zuul-gateway
zuul:
  routes:
    myUser.serviceId: aigou-plat
    myUser.path: "/plat/**"      #把以这个打头的路径都转为provider(这是对应的服务名)
  ignored-services: "*"
  prefix: /services     #统一加的前缀
