server:
  port: 8010
  max-http-header-size: 1048576
  tomcat:
      max-http-post-size: 1048576
spring:
  application:
    name: aigou-common
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300 
  