server:
  port: 8009
spring:
  application:
    name: aigou-plat
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: aigou666
    prefer-ip-address: true
