server:
  port: 9527
spring:
  application:
    name: aigou-plat-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: zuul
    prefer-ip-address: true
