server:
  port: 9527
spring:
  application:
    name: aigou-zuul-gateway
zuul:
  routes:
    myUser.serviceId: aigou-plat
    myUser.path: /plat/** 
  ignored-services: "*"
  prefix: /services     
  