server:
  port: 9527
spring:
  application:
    name: aigou-zuul-gateway
zuul:
  routes:
    myUser.serviceId: aigou-plat
    myUser.path: /plat/** 
    myProduct.serviceId: aigou-product
    myProduct.path: /product/**
  ignored-services: "*"
  prefix: /services     
  