server:
  port: 8002
spring:
  application:
    name: aigou-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbcwork
    username: root
    password: 1219
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query
